### ISSUE TITLE
error: 'float_t' does not name a type  ;I compile for Arduino UNO

### ISSUE THREAD

**Issue by rossi1772** [stm32duino/ASM330LHH#3]
\Documents\Arduino\libraries\ASM330LHH-main\src/asm330lhh_reg.h:588:8: error: 'float_t' does not name a type; did you mean 'float'?
 extern float_t asm330lhh_from_fs4g_to_mg(int16_t lsb);

**Comment by fpistm** [comment]
Fix available with v2.0.1
