### ISSUE TITLE
SAMD support

### ISSUE THREAD

**Issue by medfx** [stm32duino/ASM330LHH#6]
Hi,
do you have any plans to also support the SAMD platform?

`WARNING: library STM32duino ASM330LHH claims to run on stm32, avr, sam architecture(s) and may be incompatible with your current board which runs on samd architecture(s).`

Or is this warning wrong?

Many thanks!

**Comment by cparata** [comment]
Hello @medfx ,
basically the library should be compatible with SAMD platforms, but I don't have this kind of platforms to test. Could you test the library and tell me if it works? If so, I will update the library properties to support explicitly also the SAMD platforms.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Close as no feedback from OP.
If someone tested with SAMD or other arch, please tell us then we will update the:
https://github.com/stm32duino/ASM330LHH/blob/4b9b4b0f548472a3012481c2fd2939cae8d914a1/library.properties#L9
